from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from cti_pipeline.storage.sqlite_store import SQLiteStore


def build_stix_bundle(store: SQLiteStore, days: int = 7, limit: int = 50) -> dict[str, Any]:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    objects: list[dict[str, Any]] = []

    for trend in store.entity_trends(days=days, limit=limit):
        if trend["type"] == "cve":
            objects.append(
                {
                    "type": "vulnerability",
                    "spec_version": "2.1",
                    "id": f"vulnerability--{uuid4()}",
                    "created": now,
                    "modified": now,
                    "name": trend["value"],
                    "description": f"{trend['mentions']} mention(s), {trend['source_count']} source(s), {trend['confirmation']}",
                    "external_references": [{"source_name": "cve", "external_id": trend["value"]}],
                }
            )
        elif trend["type"] == "attack_technique":
            objects.append(
                {
                    "type": "attack-pattern",
                    "spec_version": "2.1",
                    "id": f"attack-pattern--{uuid4()}",
                    "created": now,
                    "modified": now,
                    "name": trend["value"],
                    "description": f"Observed ATT&CK technique reference: {trend['value']}",
                    "external_references": [{"source_name": "mitre-attack", "external_id": trend["value"]}],
                }
            )
        elif trend["type"] in {"domain", "ip", "url", "md5", "sha1", "sha256"}:
            objects.append(
                {
                    "type": "indicator",
                    "spec_version": "2.1",
                    "id": f"indicator--{uuid4()}",
                    "created": now,
                    "modified": now,
                    "name": trend["value"],
                    "pattern": _indicator_pattern(trend["type"], trend["value"]),
                    "pattern_type": "stix",
                    "valid_from": now,
                }
            )

    objects.append(
        {
            "type": "report",
            "spec_version": "2.1",
            "id": f"report--{uuid4()}",
            "created": now,
            "modified": now,
            "name": f"OSINT CTI Export - Last {days} Days",
            "description": "Educational STIX-style export generated by the CTI capstone pipeline.",
            "published": now,
            "report_types": ["threat-report"],
            "object_refs": [obj["id"] for obj in objects],
        }
    )

    return {"type": "bundle", "id": f"bundle--{uuid4()}", "objects": objects}


def _indicator_pattern(entity_type: str, value: str) -> str:
    if entity_type == "domain":
        return f"[domain-name:value = '{value}']"
    if entity_type == "ip":
        return f"[ipv4-addr:value = '{value}']"
    if entity_type == "url":
        return f"[url:value = '{value}']"
    return f"[file:hashes.'{entity_type.upper()}' = '{value}']"

